### ISSUE TITLE
Host it in our own servers instead of GitHub Pages

### ISSUE THREAD

**Issue by carlosnaguilera** [emilbaehr/automatic-app-landing-page#49]
As I have my own server, I would prefer to host the page on it instead of hosting it in GitHub Pages. How could I do that? Is there a way to download the theme locally and then work just with it? I looked for the gem theme but I didn't find it.

Is there a way to avoid GitHub to publish automatically the generated site?

Thank you

**Comment by carlosnaguilera** [comment]
We can just disable GitHub Pages in the Settings of the repository. Settings\Options, scroll down to GitHub Pages section and select `None` as Source

**Comment by Shouheng88** [comment]
After disabled the Github Page, how could we host it on our own server?
