### ISSUE TITLE
Make this repo a template so we can use it multiple times

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [emilbaehr/automatic-app-landing-page#51]

**Comment by cowlibob** [comment]
I forked, then set my copy to a template. I'm currently running two landing pages using this most excellent project. Thanks @emilbaehr !

**Comment by emilbaehr** [comment]
Great point! I did not know that was possible. Thanks!

**Comment by YazeedAlKhalaf** [comment]
@emilbaehr Thanks! 🚀🙏
