### ISSUE TITLE
<title> is not automatically populated

### ISSUE THREAD

**Issue by jschmid** [emilbaehr/automatic-app-landing-page#7]
If you look at head.html, you see

```html
<title>{{ site.app_name }}</title>
```

The page title is using the config. However by default it the title is not configured and the content is taken from iTunes so it "seems" to work. 

It would be nice to also change the page title when it is loaded from iTunes.

**Comment by QYL** [comment]
> If you look at head.html, you see
> 
> ```
> <title>{{ site.app_name }}</title>
> ```
> 
> The page title is using the config. However by default it the title is not configured and the content is taken from iTunes so it "seems" to work.
> 
> It would be nice to also change the page title when it is loaded from iTunes.

See 365f5b5 

I've fixed the bug and added support for customize the title.

**Comment by jschmid** [comment]
Great!

**Comment by emilbaehr** [comment]
Nice fixes. Thanks for helping out!
