### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by PauloxD** [emilbaehr/automatic-app-landing-page#8]
Good morning/afternoon/evening (depending on where you are in the world)

Firstly, I love this repo, I think it is a brilliant idea, and to the creator I would like to say a massive thank you.

This isn't really an 'issue', but more of an assistance request, and if anyone can help, I would greatly appreciate it.

I am basically trying to add a privacy policy and terms of use page, as Apple requires it for all iOS apps. Where should I place extra pages, to take advantage of Jekyll (which I am ashamed to say, I have never used)?

Any help would be great, even an article :)  

Thanks guys.

**Comment by jschmid** [comment]
Hi @PauloxD,

I need the same. You can just put your html files in the root folder, and they will be available from the website. (I mean, if you know the url)

**Comment by getaaron** [comment]
Would love a basic article template that can render markdown (same use case - `privacy.md` and `terms.md`)

Maybe add them as nav items at the top (where the press kit goes)

**Comment by emilbaehr** [comment]
Hi all! I've now released a large 2.0 update to this tool. It adresses some of the things mentioned in this issue. Hope it's useful to you!

**New features**

📝 Include a Privacy Policy page by editing privacypolicy.md
🕒 Keep a changelog page with CHANGELOG.md
🖥 Create additional pages by adding markdown files to _pages directory

**Other changes**

✅ New font stack which primarily utilises the system fonts available on the user’s computer
✅ Responsiveness improvements on iPhone SE size devices
✅ New responsive header navigation to support multiple navigation items
